### PR TITLE
fixes url for "Hits" (page views) badge

### PR DESCRIPTION
**Pull request by nelsonic**
https://github.com/dwyl/repo-badges/issues/27 & #24

### CODE REVIEW

**Comment by Satyamkr20** [comment]
my hits is also not working pls help.

**Comment by ElectricRCAircraftGuy** [comment]
> my hits is also not working pls help.

Same here.

**Comment by Satyamkr20** [comment]
@ElectricRCAircraftGuy  bro instead of hits I suggest you to use views. view working perfectly.

**Comment by Satyamkr20** [comment]
@ElectricRCAircraftGuy 

ViewCount

**Comment by Satyamkr20** [comment]
ViewCount

**Comment by ElectricRCAircraftGuy** [comment]
> @ElectricRCAircraftGuy bro instead of hits I suggest you to use views. views working perfectly.

@Satyamkr20 , this? https://github.com/wesky93/views

**Comment by Satyamkr20** [comment]
@ElectricRCAircraftGuy  yup!!

**Pull request merged**
